#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# 테스트 실행
npm test
if [ $? -ne 0 ]; then
  echo "❌ Tests failed. Commit aborted."
  exit 1
fi

# Lint-Staged 실행
npx lint-staged
if [ $? -ne 0 ]; then
  echo "❌ Linting failed. Commit aborted."
  exit 1
fi

echo "✅ All checks passed. Proceeding with commit."
